from typing import List

from zip_lm.utils import PyCorpusSentences

class PyCorpusBytes:
    def __init__(self, items: List[bytes]) -> None: ...
    def items(self) -> List[List[int]]: ...

class PyBootstrapZipModel:
    def __init__(self, items: PyCorpusBytes, b: int, n: int, t_type: int) -> None: ...
    def get_log_likelyhood(self, data: bytes) -> float: ...

class PySoftmaxZipModel:
    def __init__(self, items: PyCorpusBytes, sample_size: int, t_type: int) -> None: ...
    def get_log_likelyhood(self, data: bytes) -> float: ...

def bytes_pycorpus(sentences: PyCorpusSentences) -> PyCorpusBytes: ...
